[unix_http_server]
file=/tmp/supervisor.sock
chmod=0700
username=local
password={SHA}6464311d8049902eeaf80860cb7ff1ec4e8927a9

[supervisord]
nodaemon=true
user=root
logfile=/dev/null
pidfile=/tmp/supervisord.pid
childlogdir=/tmp

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock
username=local
password=bridge-local-only

[include]
files = /etc/supervisor/conf.d/*.conf
