pcm.!default {
  type pulse
  hint {
    show on
    description "PulseAudio Default"
  }
}

ctl.!default {
  type pulse
  hint {
    show on
    description "PulseAudio Control"
  }
}

pcm.pulse {
  type pulse
  hint {
    show on
    description "PulseAudio"
  }
}

ctl.pulse {
  type pulse
  hint {
    show on
    description "PulseAudio Control"
  }
}

pcm.bridge_mic {
  type pulse
  device "default"
  hint {
    show on
    description "Bridge Microphone"
  }
}

pcm.bridge_speaker {
  type pulse
  device "default"
  hint {
    show on
    description "Bridge Speaker"
  }
}
